version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: ''
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 7432:5432

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "AXX"
    restart: always
    container_name: 'blockscout'
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ./envs/aiax-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'ganache'
        ETHEREUM_JSONRPC_HTTP_URL: https://test-rpc.aiax.network/
        ETHEREUM_JSONRPC_WS_URL: wss://test-rpc.aiax.network/ws/
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: true
        DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
        ECTO_USE_SSL: false
    ports:
      - 4000:4000

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    restart: unless-stopped
    volumes:
      - ./nginx/main.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - blockscout